name: Run scraper

on:
  schedule:
    - cron: "0 6 * * *" # Каждый день в 6 утра по UTC
  workflow_dispatch:

jobs:
  scrape_and_update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install chromium

      - name: Run scraper
        run: python scraper.py

      - name: Commit and push updates
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/bans.csv data/failed_countries.txt
          git commit -m "🚀 Automatic daily update" || echo "No changes to commit"
          git push
